//
// InputCollectionSort.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InputCollectionSort: Codable {

    public enum Order: String, Codable, CaseIterable {
        case ascending = "Ascending"
        case descending = "Descending"
    }
    /** Collection of strings to sort */
    public var input: [String]
    /** Sort order */
    public var order: Order = .ascending

    public init(input: [String], order: Order = .ascending) {
        self.input = input
        self.order = order
    }

}

