//
// InputCollectionConversion.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InputCollectionConversion: Codable {

    /** Collection containing strings to convert */
    public var input: [String]
    /** Collection name */
    public var name: String

    public init(input: [String], name: String) {
        self.input = input
        self.name = name
    }

}

