//
// InputCurrencyFormat.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct InputCurrencyFormat: Codable {

    public enum Target: String, Codable, CaseIterable {
        case usd = "USD"
        case aud = "AUD"
        case bgn = "BGN"
        case brl = "BRL"
        case cad = "CAD"
        case chf = "CHF"
        case cny = "CNY"
        case czk = "CZK"
        case dkk = "DKK"
        case eur = "EUR"
        case gbp = "GBP"
        case hkd = "HKD"
        case hrk = "HRK"
        case huf = "HUF"
        case idr = "IDR"
        case ils = "ILS"
        case inr = "INR"
        case isk = "ISK"
        case jpy = "JPY"
        case krw = "KRW"
        case mxn = "MXN"
        case myr = "MYR"
        case nok = "NOK"
        case nzd = "NZD"
        case php = "PHP"
        case pln = "PLN"
        case ron = "RON"
        case rub = "RUB"
        case sgd = "SGD"
        case sek = "SEK"
        case thb = "THB"
        case _try = "TRY"
        case zar = "ZAR"
    }
    /** Amount to format */
    public var input: Double
    public var target: Target

    public init(input: Double, target: Target) {
        self.input = input
        self.target = target
    }

}

