//
// OutputMarketIndex.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct OutputMarketIndex: Codable {

    /** Date */
    public var date: String?
    /** Index symbol */
    public var symbol: String?
    /** Market exchange */
    public var exchange: String?
    /** Open value */
    public var _open: Double?
    /** High value */
    public var high: Double?
    /** Low value */
    public var low: Double?
    /** Close value */
    public var close: Double?
    /** Trading volume */
    public var volume: Double?
    /** Adjusted open value */
    public var adjOpen: Double?
    /** Adjusted high value */
    public var adjHigh: Double?
    /** Adjusted low value */
    public var adjLow: Double?
    /** Adjusted close value */
    public var adjClose: Double?
    /** Adjusted trading volume */
    public var adjVolume: Double?

    public init(date: String? = nil, symbol: String? = nil, exchange: String? = nil, _open: Double? = nil, high: Double? = nil, low: Double? = nil, close: Double? = nil, volume: Double? = nil, adjOpen: Double? = nil, adjHigh: Double? = nil, adjLow: Double? = nil, adjClose: Double? = nil, adjVolume: Double? = nil) {
        self.date = date
        self.symbol = symbol
        self.exchange = exchange
        self._open = _open
        self.high = high
        self.low = low
        self.close = close
        self.volume = volume
        self.adjOpen = adjOpen
        self.adjHigh = adjHigh
        self.adjLow = adjLow
        self.adjClose = adjClose
        self.adjVolume = adjVolume
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case date
        case symbol
        case exchange
        case _open = "open"
        case high
        case low
        case close
        case volume
        case adjOpen = "adj_open"
        case adjHigh = "adj_high"
        case adjLow = "adj_low"
        case adjClose = "adj_close"
        case adjVolume = "adj_volume"
    }

}

