/*
 * PowerTools Developer
 *
 * Apptigent PowerTools Developer Edition is a powerful suite of API endpoints for custom applications running on any stack. Manipulate text, modify collections, format dates and times, convert currency, perform advanced mathematical calculations, shorten URL's, encode strings, convert text to speech, translate content into multiple languages, process images, and more. PowerTools is the ultimate developer toolkit.
 *
 * The version of the OpenAPI document: 2021.1.01
 * Contact: support@apptigent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFilesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Files - Convert Image
        /// </summary>
        /// <remarks>
        /// Convert an image from one format to another
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream ConvertImage(string format, System.IO.Stream file);

        /// <summary>
        /// Files - Convert Image
        /// </summary>
        /// <remarks>
        /// Convert an image from one format to another
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> ConvertImageWithHttpInfo(string format, System.IO.Stream file);
        /// <summary>
        /// Files - Crop Image
        /// </summary>
        /// <remarks>
        /// Crop an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream CropImage(string position, decimal width, decimal height, System.IO.Stream file);

        /// <summary>
        /// Files - Crop Image
        /// </summary>
        /// <remarks>
        /// Crop an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> CropImageWithHttpInfo(string position, decimal width, decimal height, System.IO.Stream file);
        /// <summary>
        /// Files - File to string
        /// </summary>
        /// <remarks>
        /// Convert a file to a Base64 string
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <returns>OutputString</returns>
        OutputString FileToString(System.IO.Stream file);

        /// <summary>
        /// Files - File to string
        /// </summary>
        /// <remarks>
        /// Convert a file to a Base64 string
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <returns>ApiResponse of OutputString</returns>
        ApiResponse<OutputString> FileToStringWithHttpInfo(System.IO.Stream file);
        /// <summary>
        /// Files - Flip Image
        /// </summary>
        /// <remarks>
        /// Flip an image (horizontal or vertical)
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream FlipImage(string orientation, System.IO.Stream file);

        /// <summary>
        /// Files - Flip Image
        /// </summary>
        /// <remarks>
        /// Flip an image (horizontal or vertical)
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> FlipImageWithHttpInfo(string orientation, System.IO.Stream file);
        /// <summary>
        /// Files - Generate QR code
        /// </summary>
        /// <remarks>
        /// Generate a QR code image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream GenerateQRCode(InputQRCode inputQRCode = default(InputQRCode));

        /// <summary>
        /// Files - Generate QR code
        /// </summary>
        /// <remarks>
        /// Generate a QR code image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> GenerateQRCodeWithHttpInfo(InputQRCode inputQRCode = default(InputQRCode));
        /// <summary>
        /// Files - Resize Image
        /// </summary>
        /// <remarks>
        /// Resize an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream ResizeImage(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?));

        /// <summary>
        /// Files - Resize Image
        /// </summary>
        /// <remarks>
        /// Resize an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> ResizeImageWithHttpInfo(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?));
        /// <summary>
        /// Files - Rotate Image
        /// </summary>
        /// <remarks>
        /// Rotate an image by specified number of degrees
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream RotateImage(string degrees, System.IO.Stream file);

        /// <summary>
        /// Files - Rotate Image
        /// </summary>
        /// <remarks>
        /// Rotate an image by specified number of degrees
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> RotateImageWithHttpInfo(string degrees, System.IO.Stream file);
        /// <summary>
        /// Files - Watermark Image
        /// </summary>
        /// <remarks>
        /// Add watermark text to an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream WatermarkImage(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file);

        /// <summary>
        /// Files - Watermark Image
        /// </summary>
        /// <remarks>
        /// Add watermark text to an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> WatermarkImageWithHttpInfo(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFilesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Files - Convert Image
        /// </summary>
        /// <remarks>
        /// Convert an image from one format to another
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> ConvertImageAsync(string format, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - Convert Image
        /// </summary>
        /// <remarks>
        /// Convert an image from one format to another
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> ConvertImageWithHttpInfoAsync(string format, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Files - Crop Image
        /// </summary>
        /// <remarks>
        /// Crop an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> CropImageAsync(string position, decimal width, decimal height, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - Crop Image
        /// </summary>
        /// <remarks>
        /// Crop an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> CropImageWithHttpInfoAsync(string position, decimal width, decimal height, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Files - File to string
        /// </summary>
        /// <remarks>
        /// Convert a file to a Base64 string
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OutputString</returns>
        System.Threading.Tasks.Task<OutputString> FileToStringAsync(System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - File to string
        /// </summary>
        /// <remarks>
        /// Convert a file to a Base64 string
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OutputString)</returns>
        System.Threading.Tasks.Task<ApiResponse<OutputString>> FileToStringWithHttpInfoAsync(System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Files - Flip Image
        /// </summary>
        /// <remarks>
        /// Flip an image (horizontal or vertical)
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> FlipImageAsync(string orientation, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - Flip Image
        /// </summary>
        /// <remarks>
        /// Flip an image (horizontal or vertical)
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> FlipImageWithHttpInfoAsync(string orientation, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Files - Generate QR code
        /// </summary>
        /// <remarks>
        /// Generate a QR code image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> GenerateQRCodeAsync(InputQRCode inputQRCode = default(InputQRCode), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - Generate QR code
        /// </summary>
        /// <remarks>
        /// Generate a QR code image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> GenerateQRCodeWithHttpInfoAsync(InputQRCode inputQRCode = default(InputQRCode), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Files - Resize Image
        /// </summary>
        /// <remarks>
        /// Resize an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> ResizeImageAsync(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - Resize Image
        /// </summary>
        /// <remarks>
        /// Resize an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> ResizeImageWithHttpInfoAsync(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Files - Rotate Image
        /// </summary>
        /// <remarks>
        /// Rotate an image by specified number of degrees
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> RotateImageAsync(string degrees, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - Rotate Image
        /// </summary>
        /// <remarks>
        /// Rotate an image by specified number of degrees
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> RotateImageWithHttpInfoAsync(string degrees, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Files - Watermark Image
        /// </summary>
        /// <remarks>
        /// Add watermark text to an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> WatermarkImageAsync(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Files - Watermark Image
        /// </summary>
        /// <remarks>
        /// Add watermark text to an image
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> WatermarkImageWithHttpInfoAsync(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IFilesApi : IFilesApiSync, IFilesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class FilesApi : IFilesApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="FilesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FilesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FilesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public FilesApi(String basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FilesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public FilesApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FilesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public FilesApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Files - Convert Image Convert an image from one format to another
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream ConvertImage(string format, System.IO.Stream file)
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = ConvertImageWithHttpInfo(format, file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Convert Image Convert an image from one format to another
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> ConvertImageWithHttpInfo(string format, System.IO.Stream file)
        {
            // verify the required parameter 'format' is set
            if (format == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'format' when calling FilesApi->ConvertImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->ConvertImage");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png",
                "image/gif",
                "image/jpeg",
                "image/bmp"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("format", Org.OpenAPITools.Client.ClientUtils.ParameterToString(format)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<System.IO.Stream>("/ConvertImage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConvertImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Convert Image Convert an image from one format to another
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> ConvertImageAsync(string format, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await ConvertImageWithHttpInfoAsync(format, file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Convert Image Convert an image from one format to another
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="format">Output file format</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> ConvertImageWithHttpInfoAsync(string format, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'format' is set
            if (format == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'format' when calling FilesApi->ConvertImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->ConvertImage");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png",
                "image/gif",
                "image/jpeg",
                "image/bmp"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("format", Org.OpenAPITools.Client.ClientUtils.ParameterToString(format)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<System.IO.Stream>("/ConvertImage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ConvertImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Crop Image Crop an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream CropImage(string position, decimal width, decimal height, System.IO.Stream file)
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = CropImageWithHttpInfo(position, width, height, file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Crop Image Crop an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> CropImageWithHttpInfo(string position, decimal width, decimal height, System.IO.Stream file)
        {
            // verify the required parameter 'position' is set
            if (position == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'position' when calling FilesApi->CropImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->CropImage");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png",
                "image/gif",
                "image/jpeg",
                "image/bmp"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("position", Org.OpenAPITools.Client.ClientUtils.ParameterToString(position)); // form parameter
            localVarRequestOptions.FormParameters.Add("Width", Org.OpenAPITools.Client.ClientUtils.ParameterToString(width)); // form parameter
            localVarRequestOptions.FormParameters.Add("Height", Org.OpenAPITools.Client.ClientUtils.ParameterToString(height)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<System.IO.Stream>("/CropImage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CropImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Crop Image Crop an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> CropImageAsync(string position, decimal width, decimal height, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await CropImageWithHttpInfoAsync(position, width, height, file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Crop Image Crop an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="position">Crop start position (use negative values to reverse crop area)</param>
        /// <param name="width">Width (X-axis right, negative to reverse)</param>
        /// <param name="height">Height (Y-axis down, negative to reverse)</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> CropImageWithHttpInfoAsync(string position, decimal width, decimal height, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'position' is set
            if (position == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'position' when calling FilesApi->CropImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->CropImage");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png",
                "image/gif",
                "image/jpeg",
                "image/bmp"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("position", Org.OpenAPITools.Client.ClientUtils.ParameterToString(position)); // form parameter
            localVarRequestOptions.FormParameters.Add("Width", Org.OpenAPITools.Client.ClientUtils.ParameterToString(width)); // form parameter
            localVarRequestOptions.FormParameters.Add("Height", Org.OpenAPITools.Client.ClientUtils.ParameterToString(height)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<System.IO.Stream>("/CropImage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CropImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - File to string Convert a file to a Base64 string
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <returns>OutputString</returns>
        public OutputString FileToString(System.IO.Stream file)
        {
            Org.OpenAPITools.Client.ApiResponse<OutputString> localVarResponse = FileToStringWithHttpInfo(file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - File to string Convert a file to a Base64 string
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <returns>ApiResponse of OutputString</returns>
        public Org.OpenAPITools.Client.ApiResponse<OutputString> FileToStringWithHttpInfo(System.IO.Stream file)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->FileToString");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<OutputString>("/FileToString", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FileToString", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - File to string Convert a file to a Base64 string
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of OutputString</returns>
        public async System.Threading.Tasks.Task<OutputString> FileToStringAsync(System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<OutputString> localVarResponse = await FileToStringWithHttpInfoAsync(file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - File to string Convert a file to a Base64 string
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">Source file (10MB limit)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (OutputString)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<OutputString>> FileToStringWithHttpInfoAsync(System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->FileToString");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<OutputString>("/FileToString", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FileToString", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Flip Image Flip an image (horizontal or vertical)
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream FlipImage(string orientation, System.IO.Stream file)
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = FlipImageWithHttpInfo(orientation, file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Flip Image Flip an image (horizontal or vertical)
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> FlipImageWithHttpInfo(string orientation, System.IO.Stream file)
        {
            // verify the required parameter 'orientation' is set
            if (orientation == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'orientation' when calling FilesApi->FlipImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->FlipImage");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "*/*"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("orientation", Org.OpenAPITools.Client.ClientUtils.ParameterToString(orientation)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<System.IO.Stream>("/FlipImage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FlipImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Flip Image Flip an image (horizontal or vertical)
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> FlipImageAsync(string orientation, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await FlipImageWithHttpInfoAsync(orientation, file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Flip Image Flip an image (horizontal or vertical)
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="orientation">Horizontal or Vertical</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> FlipImageWithHttpInfoAsync(string orientation, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'orientation' is set
            if (orientation == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'orientation' when calling FilesApi->FlipImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->FlipImage");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "*/*"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("orientation", Org.OpenAPITools.Client.ClientUtils.ParameterToString(orientation)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<System.IO.Stream>("/FlipImage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("FlipImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Generate QR code Generate a QR code image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream GenerateQRCode(InputQRCode inputQRCode = default(InputQRCode))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = GenerateQRCodeWithHttpInfo(inputQRCode);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Generate QR code Generate a QR code image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> GenerateQRCodeWithHttpInfo(InputQRCode inputQRCode = default(InputQRCode))
        {
            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = inputQRCode;

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<System.IO.Stream>("/GenerateQRCode", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GenerateQRCode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Generate QR code Generate a QR code image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> GenerateQRCodeAsync(InputQRCode inputQRCode = default(InputQRCode), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await GenerateQRCodeWithHttpInfoAsync(inputQRCode, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Generate QR code Generate a QR code image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="inputQRCode"> (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> GenerateQRCodeWithHttpInfoAsync(InputQRCode inputQRCode = default(InputQRCode), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "application/json"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.Data = inputQRCode;

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<System.IO.Stream>("/GenerateQRCode", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GenerateQRCode", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Resize Image Resize an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream ResizeImage(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = ResizeImageWithHttpInfo(algorithm, units, file, height, width);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Resize Image Resize an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> ResizeImageWithHttpInfo(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?))
        {
            // verify the required parameter 'algorithm' is set
            if (algorithm == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'algorithm' when calling FilesApi->ResizeImage");

            // verify the required parameter 'units' is set
            if (units == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'units' when calling FilesApi->ResizeImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->ResizeImage");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png",
                "image/gif",
                "image/jpeg",
                "image/bmp"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("algorithm", Org.OpenAPITools.Client.ClientUtils.ParameterToString(algorithm)); // form parameter
            localVarRequestOptions.FormParameters.Add("units", Org.OpenAPITools.Client.ClientUtils.ParameterToString(units)); // form parameter
            if (height != null)
            {
                localVarRequestOptions.FormParameters.Add("height", Org.OpenAPITools.Client.ClientUtils.ParameterToString(height)); // form parameter
            }
            if (width != null)
            {
                localVarRequestOptions.FormParameters.Add("width", Org.OpenAPITools.Client.ClientUtils.ParameterToString(width)); // form parameter
            }
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<System.IO.Stream>("/ResizeImage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ResizeImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Resize Image Resize an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> ResizeImageAsync(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await ResizeImageWithHttpInfoAsync(algorithm, units, file, height, width, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Resize Image Resize an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="algorithm">Optimize output quality of the target image</param>
        /// <param name="units">Image adjustment units</param>
        /// <param name="file">Source image file</param>
        /// <param name="height">Image height (pixels or percent) (optional)</param>
        /// <param name="width">Image width (pixels or percent) (optional)</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> ResizeImageWithHttpInfoAsync(string algorithm, string units, System.IO.Stream file, decimal? height = default(decimal?), decimal? width = default(decimal?), System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'algorithm' is set
            if (algorithm == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'algorithm' when calling FilesApi->ResizeImage");

            // verify the required parameter 'units' is set
            if (units == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'units' when calling FilesApi->ResizeImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->ResizeImage");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "image/png",
                "image/gif",
                "image/jpeg",
                "image/bmp"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("algorithm", Org.OpenAPITools.Client.ClientUtils.ParameterToString(algorithm)); // form parameter
            localVarRequestOptions.FormParameters.Add("units", Org.OpenAPITools.Client.ClientUtils.ParameterToString(units)); // form parameter
            if (height != null)
            {
                localVarRequestOptions.FormParameters.Add("height", Org.OpenAPITools.Client.ClientUtils.ParameterToString(height)); // form parameter
            }
            if (width != null)
            {
                localVarRequestOptions.FormParameters.Add("width", Org.OpenAPITools.Client.ClientUtils.ParameterToString(width)); // form parameter
            }
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<System.IO.Stream>("/ResizeImage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ResizeImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Rotate Image Rotate an image by specified number of degrees
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream RotateImage(string degrees, System.IO.Stream file)
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = RotateImageWithHttpInfo(degrees, file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Rotate Image Rotate an image by specified number of degrees
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> RotateImageWithHttpInfo(string degrees, System.IO.Stream file)
        {
            // verify the required parameter 'degrees' is set
            if (degrees == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'degrees' when calling FilesApi->RotateImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->RotateImage");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "*/*"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("degrees", Org.OpenAPITools.Client.ClientUtils.ParameterToString(degrees)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<System.IO.Stream>("/RotateImage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RotateImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Rotate Image Rotate an image by specified number of degrees
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> RotateImageAsync(string degrees, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await RotateImageWithHttpInfoAsync(degrees, file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Rotate Image Rotate an image by specified number of degrees
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="degrees">Number of degrees</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> RotateImageWithHttpInfoAsync(string degrees, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'degrees' is set
            if (degrees == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'degrees' when calling FilesApi->RotateImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->RotateImage");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "*/*"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("degrees", Org.OpenAPITools.Client.ClientUtils.ParameterToString(degrees)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<System.IO.Stream>("/RotateImage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("RotateImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Watermark Image Add watermark text to an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream WatermarkImage(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file)
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = WatermarkImageWithHttpInfo(text, font, size, color, horizontal, vertical, file);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Watermark Image Add watermark text to an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> WatermarkImageWithHttpInfo(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file)
        {
            // verify the required parameter 'text' is set
            if (text == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'text' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'font' is set
            if (font == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'font' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'color' is set
            if (color == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'color' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'horizontal' is set
            if (horizontal == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'horizontal' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'vertical' is set
            if (vertical == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'vertical' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->WatermarkImage");

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "*/*"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("text", Org.OpenAPITools.Client.ClientUtils.ParameterToString(text)); // form parameter
            localVarRequestOptions.FormParameters.Add("font", Org.OpenAPITools.Client.ClientUtils.ParameterToString(font)); // form parameter
            localVarRequestOptions.FormParameters.Add("size", Org.OpenAPITools.Client.ClientUtils.ParameterToString(size)); // form parameter
            localVarRequestOptions.FormParameters.Add("color", Org.OpenAPITools.Client.ClientUtils.ParameterToString(color)); // form parameter
            localVarRequestOptions.FormParameters.Add("horizontal", Org.OpenAPITools.Client.ClientUtils.ParameterToString(horizontal)); // form parameter
            localVarRequestOptions.FormParameters.Add("vertical", Org.OpenAPITools.Client.ClientUtils.ParameterToString(vertical)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<System.IO.Stream>("/WatermarkImage", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WatermarkImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Files - Watermark Image Add watermark text to an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> WatermarkImageAsync(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<System.IO.Stream> localVarResponse = await WatermarkImageWithHttpInfoAsync(text, font, size, color, horizontal, vertical, file, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Files - Watermark Image Add watermark text to an image
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="text">Watermark text</param>
        /// <param name="font">Text font</param>
        /// <param name="size">Font size (points)</param>
        /// <param name="color">Text color hex value</param>
        /// <param name="horizontal">Horizontal alignment</param>
        /// <param name="vertical">Vertical alignment</param>
        /// <param name="file">Source image file</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<System.IO.Stream>> WatermarkImageWithHttpInfoAsync(string text, string font, decimal size, string color, string horizontal, string vertical, System.IO.Stream file, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'text' is set
            if (text == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'text' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'font' is set
            if (font == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'font' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'color' is set
            if (color == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'color' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'horizontal' is set
            if (horizontal == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'horizontal' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'vertical' is set
            if (vertical == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'vertical' when calling FilesApi->WatermarkImage");

            // verify the required parameter 'file' is set
            if (file == null)
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file' when calling FilesApi->WatermarkImage");


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            String[] _contentTypes = new String[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "*/*"
            };


            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FormParameters.Add("text", Org.OpenAPITools.Client.ClientUtils.ParameterToString(text)); // form parameter
            localVarRequestOptions.FormParameters.Add("font", Org.OpenAPITools.Client.ClientUtils.ParameterToString(font)); // form parameter
            localVarRequestOptions.FormParameters.Add("size", Org.OpenAPITools.Client.ClientUtils.ParameterToString(size)); // form parameter
            localVarRequestOptions.FormParameters.Add("color", Org.OpenAPITools.Client.ClientUtils.ParameterToString(color)); // form parameter
            localVarRequestOptions.FormParameters.Add("horizontal", Org.OpenAPITools.Client.ClientUtils.ParameterToString(horizontal)); // form parameter
            localVarRequestOptions.FormParameters.Add("vertical", Org.OpenAPITools.Client.ClientUtils.ParameterToString(vertical)); // form parameter
            localVarRequestOptions.FileParameters.Add("file", file);

            // authentication (apiKeyHeader) required
            if (!String.IsNullOrEmpty(this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id")))
            {
                localVarRequestOptions.HeaderParameters.Add("X-IBM-Client-Id", this.Configuration.GetApiKeyWithPrefix("X-IBM-Client-Id"));
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<System.IO.Stream>("/WatermarkImage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WatermarkImage", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
