=begin
#PowerTools Developer

#Apptigent PowerTools Developer Edition is a powerful suite of API endpoints for custom applications running on any stack. Manipulate text, modify collections, format dates and times, convert currency, perform advanced mathematical calculations, shorten URL's, encode strings, convert text to speech, translate content into multiple languages, process images, and more. PowerTools is the ultimate developer toolkit.

The version of the OpenAPI document: 2021.1.01
Contact: support@apptigent.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.0.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::InputMarketIndex
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::InputMarketIndex do
  let(:instance) { OpenapiClient::InputMarketIndex.new }

  describe 'test an instance of InputMarketIndex' do
    it 'should create an instance of InputMarketIndex' do
      expect(instance).to be_instance_of(OpenapiClient::InputMarketIndex)
    end
  end
  describe 'test attribute "symbol"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["DJA.INDX (Dow Jones Composite Average)", "DJI.INDX (Dow Jones Industrial Average)", "DJT.INDX (Dow Jones Transportation)", "DJUS.INDX (Dow Jones US)", "DXY.INDX (US Dollar Index)", "GDOW.INDX (Global Dow USD)", "NY.INDX (NYSE US 100 Index)", "NYA.INDX (NYSE Composite)", "IXIC.INDX (NASDAQ Composite)", "NDX.INDX (NASDAQ 100)", "GSPC.INDX (S&P 500)", "ES.INDX (S&P 500 Futures)", "MID.INDX (S&P Midcap 400)", "GPTSE.INDX (S&P TSX Composite Index [Canada])", "FTSE.INDX (FTSE 100 Index [UK])", "CDAXX.INDX (DAX Composite Index [Germany])", "GDAXI.INDX (DAX Index [Germany])", "HSCE.INDX (Hang Seng China Enterprise (CEI))", "HSI.INDX (Hang Seng Index [Hong Kong])", "N100.INDX (EuroNext 100)", "N225.INDX (Nikkei 225 Index)", "RTSI.INDX (RTSI Index [Russia])", "SSEC.INDX (Shanghai Composite)", "SSMI.INDX (Swiss Market Index)"])
      # validator.allowable_values.each do |value|
      #   expect { instance.symbol = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "date"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
