/*
 * PowerTools Developer
 *
 * Apptigent PowerTools Developer Edition is a powerful suite of API endpoints for custom applications running on any stack. Manipulate text, modify collections, format dates and times, convert currency, perform advanced mathematical calculations, shorten URL's, encode strings, convert text to speech, translate content into multiple languages, process images, and more. PowerTools is the ultimate developer toolkit.
 *
 * The version of the OpenAPI document: 2021.1.01
 * Contact: support@apptigent.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing InputJsonConversionHTML
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InputJsonConversionHTMLTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InputJsonConversionHTML
        //private InputJsonConversionHTML instance;

        public InputJsonConversionHTMLTests()
        {
            // TODO uncomment below to create an instance of InputJsonConversionHTML
            //instance = new InputJsonConversionHTML();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InputJsonConversionHTML
        /// </summary>
        [Fact]
        public void InputJsonConversionHTMLInstanceTest()
        {
            // TODO uncomment below to test "IsType" InputJsonConversionHTML
            //Assert.IsType<InputJsonConversionHTML>(instance);
        }


        /// <summary>
        /// Test the property 'Input'
        /// </summary>
        [Fact]
        public void InputTest()
        {
            // TODO unit test for the property 'Input'
        }
        /// <summary>
        /// Test the property 'Header'
        /// </summary>
        [Fact]
        public void HeaderTest()
        {
            // TODO unit test for the property 'Header'
        }
        /// <summary>
        /// Test the property 'Alternate'
        /// </summary>
        [Fact]
        public void AlternateTest()
        {
            // TODO unit test for the property 'Alternate'
        }
        /// <summary>
        /// Test the property 'Attributes'
        /// </summary>
        [Fact]
        public void AttributesTest()
        {
            // TODO unit test for the property 'Attributes'
        }
        /// <summary>
        /// Test the property 'Omit'
        /// </summary>
        [Fact]
        public void OmitTest()
        {
            // TODO unit test for the property 'Omit'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }

    }

}
