/**
 * PowerTools Developer
 * Apptigent PowerTools Developer Edition is a powerful suite of API endpoints for custom applications running on any stack. Manipulate text, modify collections, format dates and times, convert currency, perform advanced mathematical calculations, shorten URL\'s, encode strings, convert text to speech, translate content into multiple languages, process images, and more. PowerTools is the ultimate developer toolkit.
 *
 * The version of the OpenAPI document: 2021.1.01
 * Contact: support@apptigent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InputVerifyHash {
    /**
    * Original source string
    */
    'input': string;
    /**
    * Hash algorithm
    */
    'algorithm': InputVerifyHash.AlgorithmEnum;
    /**
    * Hashed result
    */
    'hash': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "input",
            "baseName": "input",
            "type": "string"
        },
        {
            "name": "algorithm",
            "baseName": "algorithm",
            "type": "InputVerifyHash.AlgorithmEnum"
        },
        {
            "name": "hash",
            "baseName": "hash",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InputVerifyHash.attributeTypeMap;
    }
}

export namespace InputVerifyHash {
    export enum AlgorithmEnum {
        Md5 = <any> 'MD5',
        Sha1 = <any> 'SHA1',
        Sha256 = <any> 'SHA256',
        Sha384 = <any> 'SHA384',
        Sha512 = <any> 'SHA512'
    }
}
