/**
 * PowerTools Developer
 * Apptigent PowerTools Developer Edition is a powerful suite of API endpoints for custom applications running on any stack. Manipulate text, modify collections, format dates and times, convert currency, perform advanced mathematical calculations, shorten URL\'s, encode strings, convert text to speech, translate content into multiple languages, process images, and more. PowerTools is the ultimate developer toolkit.
 *
 * The version of the OpenAPI document: 2021.1.01
 * Contact: support@apptigent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InputTranslateString {
    /**
    * String containing the text to be translated
    */
    'input': string;
    /**
    * Translation language
    */
    'language': InputTranslateString.LanguageEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "input",
            "baseName": "input",
            "type": "string"
        },
        {
            "name": "language",
            "baseName": "language",
            "type": "InputTranslateString.LanguageEnum"
        }    ];

    static getAttributeTypeMap() {
        return InputTranslateString.attributeTypeMap;
    }
}

export namespace InputTranslateString {
    export enum LanguageEnum {
        Arabic = <any> 'Arabic',
        ChineseSimplified = <any> 'Chinese (Simplified)',
        Czech = <any> 'Czech',
        Danish = <any> 'Danish',
        Dutch = <any> 'Dutch',
        English = <any> 'English',
        Finnish = <any> 'Finnish',
        French = <any> 'French',
        German = <any> 'German',
        Greek = <any> 'Greek',
        Hindi = <any> 'Hindi',
        Hungarian = <any> 'Hungarian',
        Italian = <any> 'Italian',
        Japanese = <any> 'Japanese',
        Klingon = <any> 'Klingon',
        Korean = <any> 'Korean',
        Norweigan = <any> 'Norweigan',
        Polish = <any> 'Polish',
        Portuguese = <any> 'Portuguese',
        Russian = <any> 'Russian',
        Spanish = <any> 'Spanish',
        Swedish = <any> 'Swedish',
        Turkish = <any> 'Turkish',
        Vietnamese = <any> 'Vietnamese',
        Welsh = <any> 'Welsh'
    }
}
