/**
 * PowerTools Developer
 * Apptigent PowerTools Developer Edition is a powerful suite of API endpoints for custom applications running on any stack. Manipulate text, modify collections, format dates and times, convert currency, perform advanced mathematical calculations, shorten URL\'s, encode strings, convert text to speech, translate content into multiple languages, process images, and more. PowerTools is the ultimate developer toolkit.
 *
 * The version of the OpenAPI document: 2021.1.01
 * Contact: support@apptigent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class InputCollectionSplit {
    /**
    * Collection of items to split
    */
    'input': Array<string>;
    /**
    * String to match (explicit, case-insensitive, leave empty to use Index)
    */
    'match'?: string;
    /**
    * Index location to split (leave empty to use Match value)
    */
    'index'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "input",
            "baseName": "input",
            "type": "Array<string>"
        },
        {
            "name": "match",
            "baseName": "match",
            "type": "string"
        },
        {
            "name": "index",
            "baseName": "index",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return InputCollectionSplit.attributeTypeMap;
    }
}

